insert into Countries (Name) values ('Canada');
insert into Countries (Name) values ('U.S.A');

insert into ProvincesAndStates (Name, CountryID) values ('Ontario', 1);
insert into ProvincesAndStates (Name, CountryID) values ('Quebec', 1);
insert into ProvincesAndStates (Name, CountryID) values ('British Columbia', 1);
insert into ProvincesAndStates (Name, CountryID) values ('Alberta', 1);
insert into ProvincesAndStates (Name, CountryID) values ('Manitoba', 1);
insert into ProvincesAndStates (Name, CountryID) values ('Saskatchewan', 1);
insert into ProvincesAndStates (Name, CountryID) values ('Nova Scotia', 1);
insert into ProvincesAndStates (Name, CountryID) values ('New Brunswick', 1);
insert into ProvincesAndStates (Name, CountryID) values ('Newfoundland and Labrador', 1);
insert into ProvincesAndStates (Name, CountryID) values ('Prince Edward Island', 1);
insert into ProvincesAndStates (Name, CountryID) values ('Northwest Territories', 1);
insert into ProvincesAndStates (Name, CountryID) values ('Yukon', 1);
insert into ProvincesAndStates (Name, CountryID) values ('Nunavut', 1);
insert into ProvincesAndStates (Name, CountryID) values ('Delaware', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Pennsylvania', 2);
insert into ProvincesAndStates (Name, CountryID) values ('New Jersey', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Georgia', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Connecticut', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Massachusetts', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Maryland', 2);
insert into ProvincesAndStates (Name, CountryID) values ('South Carolina', 2);
insert into ProvincesAndStates (Name, CountryID) values ('New Hampshire', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Virginia', 2);
insert into ProvincesAndStates (Name, CountryID) values ('New York', 2);
insert into ProvincesAndStates (Name, CountryID) values ('North Carolina', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Rhode Island', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Vermont', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Kentucky', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Tennessee', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Ohio', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Louisiana', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Indiana', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Mississippi', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Illinois', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Alabama', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Maine', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Missouri', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Arkansas', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Michigan', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Florida', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Texas', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Iowa', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Wisconsin', 2);
insert into ProvincesAndStates (Name, CountryID) values ('California', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Minnesota', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Oregon', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Kansas', 2);
insert into ProvincesAndStates (Name, CountryID) values ('West Virginia', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Nevada', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Nebraska', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Colorado', 2);
insert into ProvincesAndStates (Name, CountryID) values ('North Dakota', 2);
insert into ProvincesAndStates (Name, CountryID) values ('South Dakota', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Montana', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Washington', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Idaho', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Wyoming', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Utah', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Oklahoma', 2);
insert into ProvincesAndStates (Name, CountryID) values ('New Mexico', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Arizona', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Alaska', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Hawaii', 2);