insert into Countries (Name) values ('Canada');
insert into Countries (Name) values ('U.S.A');

insert into ProvincesAndStates (Name, CountryID) values ('Ontario', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Quebec', 2);
insert into ProvincesAndStates (Name, CountryID) values ('British Columbia', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Alberta', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Manitoba', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Saskatchewan', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Nova Scotia', 2);
insert into ProvincesAndStates (Name, CountryID) values ('New Brunswick', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Newfoundland and Labrador', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Prince Edward Island', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Northwest Territories', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Yukon', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Nunavut', 2);
insert into ProvincesAndStates (Name, CountryID) values ('Delaware', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Pennsylvania', 3);
insert into ProvincesAndStates (Name, CountryID) values ('New Jersey', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Georgia', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Connecticut', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Massachusetts', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Maryland', 3);
insert into ProvincesAndStates (Name, CountryID) values ('South Carolina', 3);
insert into ProvincesAndStates (Name, CountryID) values ('New Hampshire', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Virginia', 3);
insert into ProvincesAndStates (Name, CountryID) values ('New York', 3);
insert into ProvincesAndStates (Name, CountryID) values ('North Carolina', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Rhode Island', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Vermont', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Kentucky', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Tennessee', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Ohio', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Louisiana', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Indiana', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Mississippi', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Illinois', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Alabama', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Maine', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Missouri', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Arkansas', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Michigan', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Florida', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Texas', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Iowa', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Wisconsin', 3);
insert into ProvincesAndStates (Name, CountryID) values ('California', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Minnesota', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Oregon', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Kansas', 3);
insert into ProvincesAndStates (Name, CountryID) values ('West Virginia', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Nevada', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Nebraska', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Colorado', 3);
insert into ProvincesAndStates (Name, CountryID) values ('North Dakota', 3);
insert into ProvincesAndStates (Name, CountryID) values ('South Dakota', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Montana', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Washington', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Idaho', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Wyoming', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Utah', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Oklahoma', 3);
insert into ProvincesAndStates (Name, CountryID) values ('New Mexico', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Arizona', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Alaska', 3);
insert into ProvincesAndStates (Name, CountryID) values ('Hawaii', 3);