INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('10Line',1,700.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('10Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('10LineDbl',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('10LineDbl',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('12Line',1,800.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('12Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('12Line - 6Line + 6Line',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('12Line - 6Line + 6Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('12LineDbl',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('12LineDbl',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('12Wheel',1,170.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('12Wheel',0,140.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('14Line',1,1000.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('14Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('14Line - 6Line + 8Line',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('14Line - 6Line + 8Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('14LineDbl',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('14LineDbl',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('16Line - 8Line + 8Line',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('16Line - 8Line + 8Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('16Wheel',1,225.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('16Wheel',0,160.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('18Line',1,1300.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('18Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('18Line - 10Line + 8Line',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('18Line - 10Line + 8Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('20Line',1,1500.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('20Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('20Line - 10Line + 10Line',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('20Line - 10Line + 10Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('20Wheel',1,245.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('20Wheel',0,190.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('22Line - 10Line + 12Line',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('22Line - 10Line + 12Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('24Line - 12Line + 12Line',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('24Line - 12Line + 12Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('24Wheel',1,245.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('24Wheel',0,190.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('32Wheel',1,270.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('32Wheel',0,205.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('40Wheel',1,300.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('40Wheel',0,240.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('48Wheel',1,335.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('48Wheel',0,270.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('4Wheel',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('4Wheel',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('52Wheel',1,360.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('52Wheel',0,290.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('60Wheel',1,360.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('60Wheel',0,290.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('64Wheel',1,375.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('64Wheel',0,310.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('6Line',1,600.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('6Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('6LineDbl',1,540.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('6LineDbl',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('76Wheel',1,400.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('76Wheel',0,370.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('7Axle',1,265.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('7Axle',0,225.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('8Line',1,650.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('8Line',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('8LineDbl',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('8LineDbl',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('8Wheel',1,155.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('8Wheel',0,125.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('96wheel',1,750.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('96wheel',0,680.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('9Axle',1,265.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('9Axle',0,225.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Bobcat',1,95.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Bobcat',0,95.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Bull Moose - 0 Swamper',1,190.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Bull Moose - 0 Swamper',0,190.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Bull Moose - 1 Swamper',1,225.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Bull Moose - 1 Swamper',0,225.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Compressor Tarping',1,700.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Compressor Tarping',0,700.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Contractor',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Contractor',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Cooler Tarping',1,500.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Cooler Tarping',0,500.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('In-Town Jack',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('In-Town Jack',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Jack & Roll',1,525.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Jack & Roll',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Lease Operator Equipment',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Lease Operator Equipment',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Lima Crane - 0 Swamper',1,290.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Lima Crane - 0 Swamper',0,290.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Lima Crane - 1 Swamper',1,325.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Lima Crane - 1 Swamper',0,325.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Other',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Other',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Out-Town Jack',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Out-Town Jack',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Pilot Car',1,80.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Pilot Car',0,80.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Pull Tractor',1,225.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Pull Tractor',0,225.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Push Tractor',1,225.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('PushTractor',0,225.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Rigging - Bull Moose',1,415.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Rigging - Bull Moose',0,415.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Rigging - Lima Crane',1,525.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Rigging - Lima Crane',0,525.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Route Study',1,95.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Route Study',0,95.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Shop',1,85.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Shop',0,85.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Storage',1,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Storage',0,NULL);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Subsistence',1,175.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Subsistence',0,175.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Supervisor',1,110.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Supervisor',0,110.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Swamper',1,65.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Swamper',0,75.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Tandem Picker',1,245.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Tandem Picker',0,245.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Tandem Tractor',1,125.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Tandem Tractor',0,125.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Tandem Winch Tractor',1,145.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Tandem Winch Tractor',0,145.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Trojan Loader',1,170.00);
INSERT INTO Rates (Name, IsSpecialized, Hourly) VALUES ('Trojan Loader',0,170.00);