insert into ServiceTypes (Name) values ('Bed Truck');
insert into ServiceTypes (Name) values ('Bridge');
insert into ServiceTypes (Name) values ('Cats');
insert into ServiceTypes (Name) values ('Cranemats / Rigmats');
insert into ServiceTypes (Name) values ('Cranes');
insert into ServiceTypes (Name) values ('Equipment Rental');
insert into ServiceTypes (Name) values ('Hired Trucking');
insert into ServiceTypes (Name) values ('Hot Shot Service');
insert into ServiceTypes (Name) values ('Jack and Roll / Rigging');
insert into ServiceTypes (Name) values ('Light Swinging');
insert into ServiceTypes (Name) values ('Loading/Unloading');
insert into ServiceTypes (Name) values ('Pilot Cars');
insert into ServiceTypes (Name) values ('Police Escorts');
insert into ServiceTypes (Name) values ('Provide & Place no Parking signage');
insert into ServiceTypes (Name) values ('Railcar Tie Down');
insert into ServiceTypes (Name) values ('Railway Crossing Police');
insert into ServiceTypes (Name) values ('Rental Trailer');
insert into ServiceTypes (Name) values ('Repairs');
insert into ServiceTypes (Name) values ('Welders');
insert into ServiceTypes (Name) values ('Wirelift');